# This message is the status of the 3 interface buttons on the Create faceplate
std_msgs/Header header # Header stamp is time at which information was collected
irobot_create_msgs/Button button_1     # Left button on faceplate marked with one dot
irobot_create_msgs/Button button_power # Center Power button on faceplate
irobot_create_msgs/Button button_2     # Right button on faceplate marked with two dots
