---
hazards_vector_node:
  ros__parameters:
    # Publisher topic and rate
    publisher_topic: /hazard_detection
    publish_rate: 62.0
    subscription_topics:
      # Bumper topic
      - /bumper/event
      # Cliff topics
      - /cliff_front_left/event
      - /cliff_front_right/event
      - /cliff_side_left/event
      - /cliff_side_right/event
      # Wheel drop topics
      - /wheel_drop/left_wheel/event
      - /wheel_drop/right_wheel/event

ir_intensity_vector_node:
  ros__parameters:
    # IR intensity publisher topic
    publisher_topic: /ir_intensity
    subscription_topics:
      # IR intensity topics
      - /ir_intensity_front_center_left
      - /ir_intensity_front_center_right
      - /ir_intensity_front_left
      - /ir_intensity_front_right
      - /ir_intensity_left
      - /ir_intensity_right
      - /ir_intensity_side_left
