---
ir_intensity_vector_node:
  ros__parameters:
    # IR intensity publisher topic
    publisher_topic: /ir_intensity
    publish_rate: 62.0
    subscription_topics:
      # IR intensity topics
      - /ir_intensity_front_center_left
      - /ir_intensity_front_center_right
      - /ir_intensity_front_left
      - /ir_intensity_front_right
      - /ir_intensity_left
      - /ir_intensity_right
      - /ir_intensity_side_left
