---
hazards_vector_node:
  ros__parameters:
    # Publisher topic
    publisher_topic: /hazard_detection
    subscription_topics:
      # Bumper topic
      - /bumper/event
      # Cliff topics
      - /cliff_front_left/event
      - /cliff_front_right/event
      - /cliff_side_left/event
      - /cliff_side_right/event
      # Wheeldrop topics
      - /wheel_drop/left_wheel/event
      - /wheel_drop/right_wheel/event
