bool e_stop_on # true enables e-stop disabling drive motor power, false disables e-stop re-enabling motor power
---
bool success   # indicate successful application of command
string message # informational for result
