# Service to kidnap the robot.
# `position` is the target the position where the robot is going to be released
geometry_msgs/Vector3 position
# `yaw` is the target orientation of the robot
float64 yaw
# `time` is the target time in seconds the robot will spend in its current
# position, but up in `height` offset added to the z coordinate.
float64 time
# `height` is the offset distance added to z coordinate in the current position
# and then in the target position.
float64 height
---
